### ISSUE TITLE
Boats  조회시 isDone

### ISSUE THREAD

**Issue by gusanha** [CREW-service/BACK#5]
https://github.com/CREW-service/BACK/blob/f830200a78d04559eef08ac6430c97ef3297d3ba/routes/comments.js#L66-L77

Boats  조회시 isDone을 고려하지 않아도 되는지 확인 부탁드려요

추가로 연관관계를 이용해서 Boats와 comment에 대한 조회 메소드를 한번에 처리할 수는 없는 지 확인해주세요!

**Comment by YOONSOO7429** [comment]
마감 된 글은 글 목록에서만 사용됩니다. 마감 처리 된 글이 map에서는 보이지 않게 하고 나머지 부분에서는 보여야 합니다.
