### ISSUE TITLE
promise all

### ISSUE THREAD

**Issue by gusanha** [CREW-service/BACK#6]
https://github.com/CREW-service/BACK/blob/f830200a78d04559eef08ac6430c97ef3297d3ba/routes/mypage.js#L14-L26

두 쿼리가 동시에 실행 되어도 문제가 없다면 promise all을 사용해보시는건 어떨까요?

**Comment by YOONSOO7429** [comment]
```javascript
const [writedBoats, attendedBoatsData] = await Promise.all([
      writedBoatsPromise,
      attendedBoatsDataPromise,
    ]);
````
