### ISSUE TITLE
find

### ISSUE THREAD

**Issue by gusanha** [CREW-service/BACK#8]
https://github.com/CREW-service/BACK/blob/f830200a78d04559eef08ac6430c97ef3297d3ba/routes/boats.js#L219-L228

js의 find 함수를 사용하는 방법도 있겠네요!
``` js
const isCrew = crew.find((cr)=> cr.userId===userId)
if (isCrew) {
  return res.status(200).json({ boat, crew, comments, personType: "crew" });
}
return res.status(200).json({ boat, personType: "person" })
```
or

``` js
for (let i = 0; i < crew.length; i++) { 
    // crew일 경우 
    if (userId === crew[i].userId) {  
         return res.status(200).json({ boat, crew, comments, personType: "crew" }); 
    } 
} 
return res.status(200).json({ boat, personType: "person" })
```

or

```  js
crew.map((cr) => {
   if (cr.userId === userId) { 
        return res.status(200).json({ boat, crew, comments, personType: "crew" }) 
    }
})
return res.status(200).json({ boat, personType: "person" })
```

**Comment by YOONSOO7429** [comment]
for (let i = 0; i < crew.length; i++) {
      // crew일 경우
      if (userId === crew[i].userId) {
        return res
          .status(200)
          .json({ boat, crew, comments, personType: "crew" });
      }
    }
이렇게 수정했습니다

**Comment by YOONSOO7429** [comment]
`for (let i = 0; i < crew.length; i++) {
      // crew일 경우
      if (userId === crew[i].userId) {
        return res
          .status(200)
          .json({ boat, crew, comments, personType: "crew" });
      }
    }`
이렇게 수정했습니다.
